DROP TABLE IF EXISTS AGENT;

CREATE TABLE AGENT(
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    SURNAME VARCHAR(250) NOT NULL);

DROP TABLE IF EXISTS CHAT_SESSION;

CREATE TABLE CHAT_SESSION(
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(250) NOT NULL,
    AGENT_ID INTEGER REFERENCES AGENT(ID),
    TIME_CREATE DATETIME NOT NULL);